version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: geotag_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: geotag_images
      POSTGRES_USER: geotag_user
      POSTGRES_PASSWORD: geotag_password
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - trash_network

volumes:
  postgres_data:

networks:
  trash_network:
    driver: bridge
